#!/bin/bash

#curl https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker -o /etc/bash_completion.d/docker.sh
#curl -XGET https://raw.githubusercontent.com/docker/cli/master/contrib/completion/bash/docker > $(brew --prefix)/etc/bash_completion.d/docker


alias la="ls -lahF"
alias ll="ls -la"
alias ls="ls -GFh"

alias hg="history |grep"
alias c="clear"

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias dsrc="cd ~/src"
alias python3="python"

# IP addresses (from jess frazelle)
alias pubip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="sudo ifconfig | grep -Eo 'inet (addr:)?([0-9]*\\.){3}[0-9]*' | grep -Eo '([0-9]*\\.){3}[0-9]*' | grep -v '127.0.0.1'"

# Always enable colored `grep` output
alias grep='grep --color=auto '

alias rlbp="source ~/.bash_profile"

alias g="git"
__git_complete g __git_main

# Git
alias gcb="git checkout -b"
alias fix_dot_remote="git remote set-url origin git@github:npazo/dfiles.git"

# Docker
alias dbuild='docker build -t ${PWD##*/}:latest .'
alias drun="docker run -it --rm -v $(pwd):/tmp/src -w /tmp/src"

alias functions="declare -f | grep '^[a-z].* ()' | sed 's/{$//'"
