#!/bin/sh

set -a

# generic function to open /bin/sh for the specified docker container
dshell() {
	if [[ -z "${D_SHELL}" ]]; then
  		D_SHELL="/bin/sh"
	else
  		D_SHELL="${D_SHELL}"
	fi
	docker run --rm \
		-v "${HOME}/.aws:/root/.aws" \
		-v "$(pwd):/tmp/src" \
		-v /var/run/docker.sock:/var/run/docker.sock \
		-w /tmp/src \
		-it \
		--entrypoint=${D_SHELL} \
		$1
}

ansible(){
	docker run --rm \
		-v "$(pwd):/tmp/src" \
		-w /tmp/src \
		--name ansible \
		ansible "$@"
}

ansible-playbook(){
	docker run --rm \
		-v "$(pwd):/tmp/src" \
		-v "${HOME}/.aws:/root/.aws" \
		-v "$HOME/.ansible.cfg:/root/.ansible.cfg" \
		-v "$HOME/.ssh:/root/.ssh" \
		-w /tmp/src \
		--entrypoint ansible-playbook \
		--name ansible \
		ansible \
		"$@"
}

ansible-inventory(){
	docker run --rm \
		-v "$(pwd):/tmp/src" \
		-v "${HOME}/.aws:/root/.aws" \
		-v "$HOME/.ansible.cfg:/root/.ansible.cfg" \
		-v "$HOME/.ssh:/root/.ssh" \
		-w /tmp/src \
		--entrypoint ansible-inventory \
		--name ansible \
		ansible "$@"
}

aws(){
	docker run -it --rm \
		-v "${HOME}/.aws:/root/.aws" \
		--log-driver none \
		--name aws \
		awscli "$@"
}

mdtohtml(){
	docker run --rm \
		-v $(pwd):/tmp/src \
		--workdir=/tmp/src \
		ubuntu \
		pandoc -o temp.html $1
}

packer(){
	docker run --rm \
		-v "${HOME}/.aws:/root/.aws" \
		-v "$(pwd):/tmp/src" \
		-v /var/run/docker.sock:/var/run/docker.sock \
		-w /tmp/src \
		--name packer \
		packer "$@"
}


python(){
	docker run -it --rm \
		-v "$(pwd):/tmp/src" \
		-w /tmp/src \
		--name python \
		python "$@"
}

pythonaws(){
	env_string=""
	if [[ -f "env.ignore" ]]; then
		env_string="--env-file ./env.ignore"
	fi
	docker run -it --rm \
		-v "${HOME}/.aws:/root/.aws" \
		-v "$(pwd):/tmp/src" \
		$env_string \
		-w /tmp/src \
		--log-driver none \
		--name python \
		python "$@"
}

terraform(){
	if [[ -z "${D_IMG_VER}" ]]; then
  		VERSION="latest"
	else
  		VERSION="${D_IMG_VER}"
	fi
	docker run -it --rm \
		-v "${HOME}/.aws:/root/.aws" \
		-v "$(pwd):/tmp/src" \
		-v /var/run/docker.sock:/var/run/docker.sock \
		-w /tmp/src \
		--name terraform \
		terraform:${VERSION} "$@"
}
